# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Run mpms
#'
#' @param df data frame
#' @export
mpms <- function(df) {
    .Call('gpatterns_mpms', PACKAGE = 'gpatterns', df)
}

