# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Multiply a number by two
#'
#' @param x A single integer.
#' @export
timesTwo <- function(x) {
    .Call('gpatterns_timesTwo', PACKAGE = 'gpatterns', x)
}

#' Run mpms
#'
#' @param df data frame
#' @export
mpms <- function(df) {
    .Call('gpatterns_mpms', PACKAGE = 'gpatterns', df)
}

